version: '3.8'

services:
  db:
    build: .
    image: testapp-mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: "Sojt-webapp"
      MYSQL_USER: "laravel"
      MYSQL_PASSWORD: "secret"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  # phpmyadmin:
  #  image: phpmyadmin/phpmyadmin:latest
  #  restart: unless-stopped
  #  ports:
  #    - "8080:80"
  #  environment:
  #    PMA_HOST: db
  #    PMA_PORT: 3306
  #  depends_on:
  #    - db
  #  networks:
  #    - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
